#spring.application.name=AgencyAmazon

spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/admin
    redis:
      host: localhost
      port: 6379

file:
  path: test_report.json

cache:
  ttl: 3600 # Время жизни кеша в секундах (3600 = 1 час)

data:
  refresh:
    interval: 60 # Время циклического обновления данных в секундах (300 = 5 минут)

token:
  ttl: 3600 # Время жизни токена в секундах (3600 = 1 час)


